LibraryLandia/Models/Book.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryLandia.Models
{
    public class Book
    {
        public int Id { get; set; }
        [DisplayName("Título")]
        public string Title { get; set; }
        [DisplayName("Autor")]
        public int AuthorId { get; set; }
        [DisplayName("Categoría")]
        public int CategoryId { get; set; }
        [DisplayName("Edición")]
        public string Edition { get; set; }
        [DisplayName("Ejemplares")]
        public long CopiesQuantity { get; set; }
        [DisplayName("Prestados")]
        public long BorrowedBooks { get; set; }

        [DisplayName("Disponibles")]
        [NotMapped]
        public long AvailableBooks => CopiesQuantity - BorrowedBooks;

        #region Collections
        [DisplayName("Autor")]
        public Author Author { get; set; }
        [DisplayName("Categoría")]
        public Category Category { get; set; }
        #endregion
    }
}

LibraryLandia/Controllers/BooksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryLandia.Data;
using LibraryLandia.Models;

namespace LibraryLandia.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryLandiaContext _context;

        public BooksController(LibraryLandiaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewBag.SortOrder = sortOrder;
            
            var libraryLandiaContext = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Category);

            IOrderedQueryable<Book> books;
            
            switch (sortOrder)
            {
                case "category_desc":
                    books  = libraryLandiaContext.OrderByDescending(s => s.Category.Name);
                    break;
                case "category_asc":
                    books  = libraryLandiaContext.OrderBy(s => s.Category.Name);
                    break;
                default:
                    books = libraryLandiaContext.OrderBy(s => s.Id);
                    break;
            }

            var list = await books.ToListAsync();

            return View(list);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name");
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,AuthorId,CategoryId,Edition,CopiesQuantity")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", book.CategoryId);
            return View(book);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", book.CategoryId);
            return View(book);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,AuthorId,CategoryId,Edition,CopiesQuantity")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", book.CategoryId);
            return View(book);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet, ActionName("Increment")]
        public async Task<IActionResult> Increment(int id)
        {
            var book = await _context.Books.FindAsync(id);
            book.BorrowedBooks++;

            if (book.CopiesQuantity >= book.BorrowedBooks)
            {
                _context.Books.Update(book);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet, ActionName("Decrease")]
        public async Task<IActionResult> Decrease(int id)
        {
            var book = await _context.Books.FindAsync(id);
            book.BorrowedBooks--;

            if (book.BorrowedBooks >= 0)
            {
                _context.Books.Update(book);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.Id == id);
        }
    }
}

LibraryLandia/Views/Books/Create.cshtml
@model LibraryLandia.Models.Book

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label">Autor</label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Categoría</label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Edition" class="control-label"></label>
                <input asp-for="Edition" class="form-control" />
                <span asp-validation-for="Edition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CopiesQuantity" class="control-label"></label>
                <input asp-for="CopiesQuantity" class="form-control" />
                <span asp-validation-for="CopiesQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryLandia/Views/Books/Delete.cshtml
@model LibraryLandia.Models.Book

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>¿Estas seguro que deseas eliminar este elemento?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Título
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            Edición
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edition)
        </dd>
        <dt class = "col-sm-2">
            Ejemplares
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CopiesQuantity)
        </dd>
        <dt class = "col-sm-2">
            Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd>
        <dt class = "col-sm-2">
            Categoría
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista</a>
    </form>
</div>

LibraryLandia/Views/Books/Details.cshtml
@model LibraryLandia.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Título
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            Edición
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edition)
        </dd>
        <dt class = "col-sm-2">
            Ejemplares
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CopiesQuantity)
        </dd>
        <dt class = "col-sm-2">
            Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd>
        <dt class = "col-sm-2">
            Categoría
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Regresar a la lista</a>
</div>

LibraryLandia/Views/Books/Edit.cshtml
@model LibraryLandia.Models.Book

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label">Autor</label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Categoria</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edition" class="control-label"></label>
                <input asp-for="Edition" class="form-control" />
                <span asp-validation-for="Edition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CopiesQuantity" class="control-label"></label>
                <input asp-for="CopiesQuantity" class="form-control" />
                <span asp-validation-for="CopiesQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryLandia/Views/Books/Index.cshtml
@model IEnumerable<LibraryLandia.Models.Book>

@{
    ViewData["Title"] = "Libros";
}

<h1>Libros</h1>

<p>
    <a asp-action="Create">Crear Nuevo</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AvailableBooks)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BorrowedBooks)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th colspan="4">
            Categoria
            @if (ViewBag.SortOrder == "category_asc")
            {
                <a href="@Url.Action("Index", "Books", new { sortOrder = "category_desc"  })">
                    <i asp-action="" class="bi bi-arrow-up"></i>
                </a>
            } else if (ViewBag.SortOrder == "category_desc") {
            
            <a href="@Url.Action("Index", "Books", new { sortOrder = "category_asc"  })">
                                <i class="bi bi-arrow-down"></i>
                            </a>
            }
            else
            {
                <a href="@Url.Action("Index", "Books", new { sortOrder = "category_asc"  })">
                    <i class="bi bi-arrow-down-up"></i>
                </a>
            }
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableBooks)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BorrowedBooks)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a> |
                <a asp-action="Increment" asp-route-id="@item.Id">Prestar</a> |
                <a asp-action="Decrease" asp-route-id="@item.Id">Devolver</a>
            </td>
        </tr>
    }
    </tbody>
</table>